"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { ArrowIcon, ServiceIcon } from "./icons";
import { pick, type Localized } from "@/lib/content";
import { useLanguage } from "./language-provider";

export function Reveal({children,className=""}:{children:React.ReactNode;className?:string}){const ref=useRef<HTMLDivElement>(null);const[show,setShow]=useState(false);useEffect(()=>{const node=ref.current;if(!node)return;const io=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){setShow(true);io.disconnect()}},{threshold:.12});io.observe(node);return()=>io.disconnect()},[]);return <div ref={ref} className={`reveal ${show?"is-visible":""} ${className}`}>{children}</div>}
export function ButtonLink({href,children,variant="primary"}:{href:string;children:React.ReactNode;variant?:"primary"|"secondary"|"text"}){return <Link className={`button ${variant}`} href={href}><span>{children}</span><ArrowIcon/></Link>}
export function SectionHeading({eyebrow,title,text,inverse=false}:{eyebrow:Localized;title:Localized;text?:Localized;inverse?:boolean}){const{lang}=useLanguage();return <div className={`section-heading ${inverse?"inverse":""}`}><span>{pick(eyebrow,lang)}</span><h2>{pick(title,lang)}</h2>{text&&<p>{pick(text,lang)}</p>}</div>}
export function PageHero({eyebrow,title,text,image="/rsc-about.webp",compact=false}:{eyebrow:Localized;title:Localized;text:Localized;image?:string;compact?:boolean}){const{lang}=useLanguage();return <section className={`page-hero ${compact?"compact":""}`}><img src={image} alt="" fetchPriority="high"/><div className="page-hero-overlay"/><div className="container"><span className="page-kicker">{pick(eyebrow,lang)}</span><h1>{pick(title,lang)}</h1><p>{pick(text,lang)}</p></div></section>}
export function Breadcrumb({items}:{items:Array<{label:Localized;href?:string}>}){const{lang}=useLanguage();return <nav className="breadcrumb" aria-label="Breadcrumb"><Link href="/">{lang==="ar"?"الرئيسية":"Home"}</Link>{items.map((item,i)=><span key={i}>{item.href?<Link href={item.href}>{pick(item.label,lang)}</Link>:pick(item.label,lang)}</span>)}</nav>}
export function ServiceCard({service,index}:{service:{slug:string;icon:string;title:Localized;short:Localized};index:number}){const{lang}=useLanguage();return <Link className="service-card" href={`/services/${service.slug}`}><div className="service-card-top"><span>0{index+1}</span><ServiceIcon name={service.icon}/></div><h3>{pick(service.title,lang)}</h3><p>{pick(service.short,lang)}</p><span className="card-link">{lang==="ar"?"تفاصيل الخدمة":"Explore service"}<ArrowIcon/></span></Link>}
export function CtaBand(){const{lang}=useLanguage();return <section className="cta-band"><div><span>{lang==="ar"?"مشروعك يبدأ بقرار واضح":"Your project starts with clarity"}</span><h2>{lang==="ar"?"دعنا نحوّل احتياجك إلى خطة تنفيذ قابلة للقياس.":"Let’s turn your requirement into a measurable delivery plan."}</h2></div><div><ButtonLink href="/request-quote">{lang==="ar"?"اطلب عرض سعر":"Request a quote"}</ButtonLink><ButtonLink href="/contact" variant="secondary">{lang==="ar"?"تواصل معنا":"Contact us"}</ButtonLink></div></section>}
export function EmptyProjects(){const{lang}=useLanguage();return <div className="projects-empty"><span>RSC / CASE STUDIES</span><h2>{lang==="ar"?"محفظة المشاريع الموثّقة قيد الإعداد":"Verified project portfolio in preparation"}</h2><p>{lang==="ar"?"حرصًا على الدقة والخصوصية، لن ننشر أسماء مشاريع أو عملاء أو أرقامًا غير معتمدة. تم تجهيز بنية المعرض لإضافة دراسات الحالة الحقيقية فور اعتماد بياناتها وصورها.":"To protect accuracy and confidentiality, we do not publish unverified project or client information. The portfolio structure is ready for approved case studies and imagery."}</p><ButtonLink href="/contact">{lang==="ar"?"اطلب ملف الأعمال":"Request company profile"}</ButtonLink></div>}
